version: "3.9"
services:
  web:
    build: .
    environment: 
        DISPLAY: 100.64.0.206:0.0
    volumes: 
        - /tmp/.X11-unix:/tmp/.X11-unix
        - ~/.Xauthority:/root/.Xauthority
        - .:/root/working
  #redis:
  #  image: "redis:alpine"
  #  logging:
  #    driver: "none"
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  rstudio:
    image: "rocker/rstudio"
    ports:
      - "8787:8787"
    logging:
      driver: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  git:
    image: "gitbucket/gitbucket"
    ports:
      - "8080:8080"
    logging:
      driver: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  spyder:
    image: "compdatasci/spyder-desktop"
    ports:
      - "6081:6080"
      - "5900:5900"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  jupyter-notebook:
    image: "jupyter/scipy-notebook:17aba6048f44"
    command: ['start-notebook.sh', "--NotebookApp.token=''", "--NotebookApp.password=''"]
    ports:
      - "8888:8888"
    logging:
      driver: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  visual-studio:
    image: "beneventsur/xubuntu:vscode-1.44.2"
    ports:
      - "6080:6080"
      - "5901:5901"
    environment:
      PASSWORD: 123456
      WIDTH: 1920
      HEIGHT: 1080
    logging:
      driver: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  tensorflow:
    image: "tensorflow/tfx"
    logging:
      driver: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  tableau:
    image: "pvtmert/tableau"
    logging:
      driver: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8316:8316"
  sonarqube:
    image: "sonarqube"
    logging:
      driver: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  sonarscloud:
    image: "sonarsource/sonar-scanner-cli"
    environment:
      SONAR_HOST_URL: "http://localhost:9000"
    logging:
      driver: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  hadoop:
    image: "bde2020/hadoop-datanode"
    logging:
      driver: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
#  apachespark:
#    image: "mesosphere/spark-dev"
  markdown:
    image: "v4tech/markdown-editor"
    ports:
      - "12345:80"
     