version: "3.9"
services:
  web:
    build: .
    environment: 
        DISPLAY: 100.64.0.206:0.0
    logging:
      driver: "none"
  rstudio:
    image: "rocker/rstudio"
    ports:
      - "8787:8787"
    logging:
      driver: "none"
  git:
    image: "gitbucket/gitbucket"
    ports:
      - "8080:8080"
    logging:
      driver: "none"
  spyder:
    image: "compdatasci/spyder-desktop"
    ports:
      - "6081:6080"
      - "5900:5900"
  jupyter-notebook:
    image: "jupyter/scipy-notebook:17aba6048f44"
    command: ['start-notebook.sh', "--NotebookApp.token=''", "--NotebookApp.password=''"]
    ports:
      - "8888:8888"
    logging:
      driver: "none"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  visual-studio:
    image: "beneventsur/xubuntu:vscode-1.44.2"
    ports:
      - "6080:6080"
      - "5901:5901"
    environment:
      PASSWORD: 123456
      WIDTH: 1920
      HEIGHT: 1080
    logging:
      driver: "none"
  tensorflow:
    image: "tensorflow/tensorflow:latest-jupyter"
    volumes:
      - ~/notebooks:/tf/notebooks
    ports:
      - "8890:8888"
  apachespark:
    image: "alexcoppe/pyspark"
    ports:
      - "8889:8889"
    logging:
      driver: "none" 
  markdown:
    image: "v4tech/markdown-editor"
    ports:
      - "12345:80"
     